version: '3.8'

x-common: &common
  build:
    context: .
  env_file:
    - .env
  networks:
    - localnet

services:
  gateway:
    build:
      args:
        APP_NAME: gateway
    ports:
      - 3010:3010 # Rest
    environment:
      SENTRY_DSN:

      AUTH_HOST:
      CONFIG_HOST:
      DOMAIN_HOST:
      IDENTITY_HOST:
    <<: *common

  #######################
  # AUTH SERVICE
  #######################
  auth:
    container_name: auth
    build:
      args:
        SERVICE_NAME: auth
    ports:
      - 3020:3020 # Rest
      - 5020:5020 # gRPC
    environment:
      NODE_ENV: prod
      SENTRY_DSN:

      CONFIG_HOST:
      DOMAIN_HOST:
      IDENTITY_HOST:
    <<: *common

  #######################
  # CONFIGS SERVICE
  #######################
  configs:
    container_name: configs
    build:
      args:
        SERVICE_NAME: configs
    ports:
      - 3030:3030 # Rest
      - 5030:5030 # gRPC
    environment:
      NODE_ENV: prod
      SENTRY_DSN:
    <<: *common

  #######################
  # DOMAIN SERVICES
  #######################
  domain:
    container_name: domain
    build:
      args:
        SERVICE_NAME: domain
    ports:
      - 3040:3040 # Rest
      - 5040:5040 # gRPC
    environment:
      NODE_ENV: prod
      SENTRY_DSN:
    <<: *common

  #######################
  # IDENTITY SERVICES
  #######################
  identity:
    container_name: identity
    build:
      args:
        SERVICE_NAME: identity
    ports:
      - 3050:3050 # Rest
      - 5050:5050 # gRPC
    environment:
      NODE_ENV: prod
      SENTRY_DSN:
    <<: *common

  #######################
  # SPECIAL SERVICES
  #######################
  special:
    container_name: special
    build:
      args:
        SERVICE_NAME: special
    ports:
      - 3060:3060 # Rest
    environment:
      NODE_ENV: prod
      SENTRY_DSN:
    <<: *common

  #######################
  # TOUCH SERVICES
  #######################
  touch:
    container_name: touch
    build:
      args:
        SERVICE_NAME: touch
    ports:
      - 3070:3070 # Rest
    environment:
      NODE_ENV: prod
      SENTRY_DSN:
    <<: *common

networks:
  localnet:
    driver: bridge
