receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - 'http://*'
            - 'https://*'

exporters:
  otlp:
    endpoint: 'jaeger:4318'
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
