services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.64.0
    command: [ '--memory.max-traces', '100', '--query.base-path', '/jaeger/ui' ]
    ports:
      - 16686:16686 # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - localnet

  otelcol:
    container_name: otelcol
    image: otel/opentelemetry-collector-contrib:0.115.1
    command: [ '--config=/etc/otelcol.config.yml' ]
    volumes:
      - ./config/otelcol.config.yml:/etc/otelcol.config.yml
    ports:
      - 4318:4318 # OTLP over HTTP receiver
    depends_on:
      - jaeger
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
