services:
  minio:
    container_name: minio
    image: bitnami/minio:2024
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
