services:
  #######################
  # CACHE
  #######################

  redis:
    extends:
      file: docker-compose.rds.yml
      service: redis

  #######################
  # STORAGE
  #######################

  minio:
    extends:
      file: docker-compose.mio.yml
      service: minio

  #######################
  # DATABASE
  #######################

  mongodb-primary:
    extends:
      file: docker-compose.mg.yml
      service: mongodb-primary

  mongodb-secondary:
    extends:
      file: docker-compose.mg.yml
      service: mongodb-secondary
    depends_on:
      - mongodb-primary

  mongodb-arbiter:
    extends:
      file: docker-compose.mg.yml
      service: mongodb-arbiter
    depends_on:
      - mongodb-primary
      - mongodb-secondary

  #######################
  # BROKER
  #######################

  zookeeper:
    extends:
      file: docker-compose.kfk.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.kfk.yml
      service: kafka
    depends_on:
      - zookeeper

  kafka-ui:
    extends:
      file: docker-compose.kfk.yml
      service: kafka-ui
    depends_on:
      - zookeeper
      - connect
      - kafka

  connect:
    extends:
      file: docker-compose.kfk.yml
      service: connect
    depends_on:
      - zookeeper
      - kafka

networks:
  localnet:
    driver: bridge
