version: '3.8'

services:
  structurizr:
    image: structurizr/lite:lates
    container_name: structurizr
    ports:
      - 8080:8080
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
